apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: auth
spec:
  ingressClassName: nginx
  tls:                        # ← AÑADIR ESTO
  - hosts:
    - podprompt.local
    secretName: podprompt-tls
  rules:
  - host: podprompt.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080